---
sudo: required
env:
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: centos
      VERSION: 8
    - DISTRIBUTION: oraclelinux
      VERSION: 7
# Error with dbus (systemd docker)
#    - DISTRIBUTION: oraclelinux
#      VERSION: 8
#    - DISTRIBUTION: fedora
#      VERSION: 29
    - DISTRIBUTION: fedora
      VERSION: 30
    - DISTRIBUTION: debian
      VERSION: 9
    - DISTRIBUTION: debian
      VERSION: 10
# Error with dbus (systemd docker)
#    - DISTRIBUTION: ubuntu
#      VERSION: 16.04
#    - DISTRIBUTION: ubuntu
#      VERSION: 18.04
services:
  - docker

before_install:
  # Install latest Git
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  - sudo apt-get install python-pip || sudo apt-get install python3-pip
script:
  - ./tests/docker-tests.sh --no-firewalld
