---
sudo: required
env:
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: centos
      VERSION: 8
    - DISTRIBUTION: oraclelinux
      VERSION: 7
# Errror with dbus (docker)
#    - DISTRIBUTION: oraclelinux
#      VERSION: 8
    - DISTRIBUTION: fedora
      VERSION: 30
# TODO
    - DISTRIBUTION: ubuntu
      VERSION: 16.04
    - DISTRIBUTION: ubuntu
      VERSION: 18.04
    - DISTRIBUTION: debian
      VERSION: 9
    - DISTRIBUTION: debian
      VERSION: 10
services:
  - docker

before_install:
  # Install latest Git
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  - sudo apt-get install python-pip || sudo apt-get install python3-pip
  - sudo pip install yamllint ansible-lint || sudo pip3 install yamllint ansible-lint
script:
  - ./lint.sh
  - ROLE=msaf1980.linux-base ./tests/docker-tests.sh --no-firewalld
