---
- name: Admin | Create {{ admin_group }} group
  group:
    name: "{{ admin_group }}"
    system: yes

- name: Admin | Make sure users from the wheel group can use sudo
  lineinfile:
    dest: /etc/sudoers.d/admin
    state: present
    create: true
    regexp: '^%{{ admin_group }}'
    line: '%{{ admin_group }} ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  when: not sudo_wheel_nopasswd
  tags:
    - base
    - admin

- name: Admin | Make sure users from the wheel group can use sudo
  lineinfile:
    dest: /etc/sudoers.d/admin
    state: present
    create: true
    regexp: '^%{{ admin_group }}'
    line: '%{{ admin_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  when: sudo_wheel_nopasswd
  tags:
    - base
    - admin

- name: Admin | Set attributes of sudo configuration file for wheel group
  file:
    path: /etc/sudoers.d/admin
    owner: root
    group: root
    mode: 0440
  tags:
    - base
    - admin

- name: Admin | Make sure that only users from the wheel group can use su
  lineinfile:
    dest: /etc/pam.d/su
    state: present
    create: true
    regexp: '^auth       required pam_wheel.so'
    line: 'auth       required pam_wheel.so'
  when: su_wheel_only
  tags:
    - base
    - admin
