---
- name: Admin | Make sure users from the wheel group can use sudo
  lineinfile:
    dest: /etc/sudoers.d/wheel
    state: present
    create: true
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  when: not sudo_wheel_nopasswd
  tags:
    - base
    - admin

- name: Admin | Make sure users from the wheel group can use sudo
  lineinfile:
    dest: /etc/sudoers.d/wheel
    state: present
    create: true
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  when: sudo_wheel_nopasswd
  tags:
    - base
    - admin

- name: Admin | Set attributes of sudo configuration file for wheel group
  file:
    path: /etc/sudoers.d/wheel
    owner: root
    group: root
    mode: 0440
  tags:
    - base
    - admin
