- name: Apparmor | Include task per system
  include_tasks: "apparmor-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
  when: ansible_distribution == 'Debian'

- include_tasks: "{{ ansible_distribution }}_9.yml"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int == 16

- include_tasks: "{{ ansible_distribution }}_10.yml"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int == 18
