# Set defaults (generic)
---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: base

- include_vars: debbase.yml
  when:  ansible_distribution|lower in [ 'debian', 'ubuntu' ]

- name: Reset reboot flag
  set_fact:
    reboot_needed: false
