---

- include_tasks: defaults.yml    # Default values

- include_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'

- include_tasks: debian.yml
  when: ansible_os_family|lower == 'debian'

# Generic tasks
- include_tasks: config.yml    # Configuration (/etc/)
- include_tasks: logging.yml   # Configure logging/crashdumps/etc
- include_tasks: selinux.yml  # SELinux settings
  when: selinux_config_base
- include_tasks: admin.yml     # Admin settings (a.o. sudo, etc)
- include_tasks: sshd.yml      # OpenSSHD settings
- include_tasks: firewalld.yml # Firewalld settings
  when:
    - firewalld_config_base
    - ansible_os_family|lower == 'redhat'

- include_tasks: redhat-reboot.yml
  when: ansible_os_family|lower == 'redhat'

- name: "reboot needed"
  debug: 
    msg: "{{ inventory_hostname }} need reboot"
  when: reboot_needed | default(false)
  tags:
    - base
