- name: Modprobe
  modprobe:
    name: "{{ item.name }}"
    state: present
    params: "{{ item.param | default(omit) }}"
  with_items: "{{ modprobe }}"
  when: modprobe is defined
  tags:
    - base
    - modprobe
