- name: Pip | Set proxy in /etc/pip/conf
  ini_file:
    path: /etc/pip.conf
    section: global
    option: proxy
    value: "{{ pip_proxy }}"
    mode: '0644'
  when: pip_proxy is defined and pip_proxy != ""

