# Install custom repositories and packages. Repositories should be installed
# using an RPM package. A list of URLs to the RPMs for these repositories
# should be specified in group_vars or host_vars.
---

- name: Install | Ensure the machine-ID is available
  command: systemd-machine-id-setup
  args:
    creates: /etc/machine-id
  tags: base

- name: Install | Package management configuration ({{ rhbase_package_manager }})
  template:
    src: "etc_{{ rhbase_package_manager }}.conf.j2"
    dest: "{{ rhbase_package_manager_configuration }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - base
    - install

- name: Install | Role/Ansible dependencies
  package:
    name: "{{ dependencies_base }}"
    state: present
  tags:
    - base
    - install

- name: Install | Ensure basic systemd services are running
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ rhbase_systemd_services }}"
  tags: base

- name: Install | Ensure specified external repositories are installed
  package:
    name: "{{ rhbase_repositories }}"
    state: present
  tags:
    - base
    - install

- name: Install | Ensure specified repositories from repo files are enabled
  lineinfile:
    dest: "/etc/yum.repos.d/{{ item }}.repo"
    line: 'enabled=1'
    state: present
    regexp: '^enabled='
  with_items: "{{ rhbase_enable_all_repos }}"
  tags:
    - base
    - install

- name: Install | Ensure specified repositories are enabled
  yum_repository:
    name: "{{ item }}"
    enabled: yes
  with_items: "{{ rhbase_enable_repos }}"
  tags:
    - base
    - install

- name: Install | Ensure specified repositories from repo files are disabled
  lineinfile:
    dest: "/etc/yum.repos.d/{{ item }}.repo"
    line: 'enabled=0'
    state: present
    regexp: '^enabled='
  with_items: "{{ rhbase_disable_all_repos }}"
  tags:
    - base
    - install

- name: Install | Ensure specified repositories are disabled
  yum_repository:
    name: "{{ item }}"
    enabled: no
  with_items: "{{ rhbase_disable_repos }}"
  tags:
    - base
    - install

- name: Install | Ensure specified packages are installed
  package:
    name: "{{ rhbase_install_packages }}"
    state: present
  tags:
    - base
    - install

- name: Install | Ensure specified packages are NOT installed
  package:
    name: "{{ rhbase_remove_packages }}"
    state: absent
  tags:
    - base
    - install

- name: Install | Ensure all updates are installed
  package:
    name: '*'
    state: latest
  when: update_on_install
  tags:
    - base
    - update
    - install
