---
- include_tasks: redhat-defaults.yml      # Default values
- include_tasks: redhat-install.yml       # Install repositories and packages
- include_tasks: redhat-config.yml        # Configuration (/etc/)
- include_tasks: redhat-auto-updates.yml  # Automatic updates
  when: automatic_updates
- include_tasks: redhat-services.yml       # Enable/Disable base servises
