- name: install own version of 'needs-restarting'
  template: src="redhat-needs-restarting.py.j2" dest=/root/needs-restarting.py mode=0700

- name: Reboot required (Red Hat) - Step 1
  shell: "/root/needs-restarting.py -r"
  register: reboot_required
  ignore_errors: True
  changed_when: False
  when: ansible_distribution_major_version|int < 8 # not work on RedHat 8
  tags:
    - base
    - install
    - updates

- name: Reboot required (Red Hat) - Step 2
  shell: ( /bin/sleep 5 ; shutdown -r now "Ansible updates triggered" ) &
  async: 30
  poll: 0
  when: reboot_required.rc is defined and reboot_required.rc == 1 and automatic_reboot
  tags:
    - base
    - install
    - updates

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: reboot_required.rc is defined and reboot_required.rc == 1 and automatic_reboot
  tags:
    - base
    - install
    - updates

- name: Post login
  shell: "hostname"
  register: out
  when: reboot_required.rc is defined and reboot_required.rc == 1 and automatic_reboot
  tags:
    - base
    - install
    - updates

- name: "hostname out"
  debug:
    msg: "{{ out.stdout.split('\n') }}"
  when: reboot_required.rc is defined and reboot_required.rc == 1 and automatic_reboot
  tags:
    - base
    - install
    - updates

- name: "set reboot_needed"
  set_fact:
    reboot_needed: true
  when: reboot_required.rc is defined and reboot_required.rc == 1 and reboot_check and not automatic_reboot
  tags:
    - base
    - install
    - updates
