---
- include_tasks: redhat-install.yml       # Install repositories and packages
- include_tasks: redhat-config.yml        # Configuration (/etc/)
- include_tasks: redhat-auto-updates.yml  # Automatic updates
  when: automatic_updates
