# Basic SELinux settings
---

- name: Install | SELinux/Ansible dependencies
  package:
    name: "{{ dependencies_selinux }}"
    state: present
  tags:
    - base
    - security

- name: SELinux | Make sure SELinux has the desired state ({{ selinux_state }})
  selinux:
    policy: targeted
    state: "{{ selinux_state }}"
  tags:
    - base
    - security

- name: SELinux | Enable SELinux booleans
  seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  with_items: "{{ selinux_booleans }}"
  when: selinux_state == 'enforcing' or selinux_state == 'permissive'
  tags:
    - base
    - security

- name: SELinux | Allow ports
  seport:
    ports: "{{ item.ports }}"
    proto: "{{ item.proto }}"
    setype: "{{ item.setype }}"
    state: "{{ item.state }}"
  with_items: "{{ selinux_seports }}"
